# Default values for nightscout-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nightscout:
  apisecret: mypassword1!
  image: dhermanns/rpi-nightscout

# Set "active" to true if you would like to pinpoint your nightscout backend to a certain
# kubernetes node. This is useful to not loose your mongo data if kubernetes lifts your mongodb
# to a different node:
nodeSelector:
  active: false
  # name of the kubernetes node hostname you would like to pin nightscout to:
  hostname: k3ts

# Forward incoming traffic for certain hosts to nightscout.
# Usually this are your dyndns hostnames: 
ingress:
  enabled: true
  hosts:
    - host: mynightscout.duckdns.org
    - host: night-t.lan

# Activate a default Ingress, so that nightscout is accessible for all incoming hosts using Port 80:
defaultIngress:
  enabled: true
