{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nightscout
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: nightscout-tls
      hosts:
      {{ range .Values.ingress.tlshosts }}
      - {{ .host | quote }}
      {{ end }}
  rules:
    {{ range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nightscout
                port:
                  number: 1337
    {{ end }}
{{ end }}
